"""add ai_readiness_score

Revision ID: 52ee734cb16c
Revises: 70f5c99c7a1b
Create Date: 2026-03-19 21:08:22.334117

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '52ee734cb16c'
down_revision = '70f5c99c7a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_readiness_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.drop_column('ai_readiness_score')

    # ### end Alembic commands ###
