"""add dimensions and responses

Revision ID: 70f5c99c7a1b
Revises:
Create Date: 2026-03-19 17:53:49.230161

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '70f5c99c7a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repository_url', sa.String(length=500), nullable=True),
    sa.Column('team', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maturity_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', sa.String(length=200), nullable=True),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('version_control_score', sa.Integer(), nullable=True),
    sa.Column('build_process_score', sa.Integer(), nullable=True),
    sa.Column('testing_score', sa.Integer(), nullable=True),
    sa.Column('deployment_score', sa.Integer(), nullable=True),
    sa.Column('monitoring_score', sa.Integer(), nullable=True),
    sa.Column('security_score', sa.Integer(), nullable=True),
    sa.Column('configuration_management_score', sa.Integer(), nullable=True),
    sa.Column('feedback_loops_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('config_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dimension_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('question_key', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['maturity_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dimension_responses')
    op.drop_table('pipeline_stages')
    op.drop_table('maturity_assessments')
    op.drop_table('pipelines')
    # ### end Alembic commands ###
