"""add application type classification

Revision ID: 765552021352
Revises: 52ee734cb16c
Create Date: 2026-03-19 21:29:18.617106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765552021352'
down_revision = '52ee734cb16c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('application_type_label', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classification_confidence', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maturity_assessments', schema=None) as batch_op:
        batch_op.drop_column('classification_confidence')
        batch_op.drop_column('application_type_label')
        batch_op.drop_column('application_type')

    # ### end Alembic commands ###
