"""add file_path to dimension_responses

Revision ID: de0eb4d01872
Revises: 765552021352
Create Date: 2026-03-19 21:39:31.379700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0eb4d01872'
down_revision = '765552021352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dimension_responses', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
